plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chessbuzz'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chessbuzz'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

android {
    buildFeatures {
        buildConfig true
    }
}

tasks.register('buildReactApp', Exec) {
    workingDir '..'
    commandLine 'npm', 'run', 'build'
}

tasks.register('copyReactBuildToAssets', Copy) {
    dependsOn 'buildReactApp'
    from '../dist'
    into 'src/main/assets'
}

tasks.named('preBuild') {
    dependsOn 'copyReactBuildToAssets'
}
